### ISSUE TITLE
"This email has been used too many times"

### ISSUE THREAD

**Issue by philipmulcahy** [Glench/ExtPay#246]
**Describe the bug**
See attached screenshot from extension user, showing the ExtPay login dialog rejecting a legitimate and paid user's email address with: "This email has been used too many times".
<img width="1239" alt="image" src="https://github.com/user-attachments/assets/c2b9c0e6-4278-444b-b47d-5af8c61de852">

**To Reproduce**
1) Open "Amazon Order History Reporter" chrome extension popup.
2) Click on "preview/premium features" button.
3) Click on "renew login if you've paid"

**Expected behavior**
Successful login and access to gated features.

**Screenshots**
See above

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Glench** [comment]
Please send me your email and I can reset the login limit for that account.

**Comment by philipmulcahy** [comment]
Address sent privately.
Thanks @Glench

**Comment by philipmulcahy** [comment]
User has confirmed they're up and running.
Thank you

**Comment by curlyethan** [comment]
I run Cookie Guardian, a Chrome extension using ExtPay. One of my customers has hit the login limit and is now stuck on "This email has been used too many times", so he cannot restore the Premium he bought back in April.

He is not abusing it. He uses several browser profiles for isolation, and my own restore flow gave him no feedback when a login did not take, so he retried a few times not knowing the attempts were landing on your side. That is my bug and I am fixing it.

Could you reset the login limit on his email so he can activate again? I saw you did this for someone in issue 246. Happy to send the checkout email address over however you prefer, just say the word and I will reply with it.

Two quick questions while I am here. Is the cap still 10, so I can put the right number in my own copy rather than guessing? And is there any way for a developer to see a customer's remaining activations, or to release an old one, so I can handle this myself next time instead of emailing you?

Thanks for ExtPay, it does the job well.

Cheers,
Ethan

**Comment by burkybang** [comment]
@curlyethan You can reset it yourself from your account at ExtensionPay.com
